.PHONY: clean

all: main

main: main.o Rectangle.o Circle.o
g++ main.o Rectangle.o Circle.o -o main

main.o: main.cpp
g++ -c main.cpp

Rectangle.o: Rectangle.cpp
g++ -c Rectangle.cpp

Circle.o: Circle.cpp
g++ -c Circle.cpp

clean:
rm *.o main
